name: clean_sync
description: Part of the clean framework that handles server-client synchronization.
dependencies:
  clean_ajax:
    path: https://github.com/hleumas/clean_ajax
  clean_data:
    git: https://github.com/hleumas/clean_data
  mongo_dart: any
dev_dependencies:
  clean_backend:
    path: https://github.com/hleumas/clean_backend
