name: clean_sync
description: Part of the clean framework that handles server-client synchronization.
dependencies:
  clean_ajax:
    git: https://github.com/cleandart/clean_ajax
  clean_data:
    git: https://github.com/cleandart/clean_data
  mongo_dart: any
  unittest: any
dev_dependencies:
  clean_backend:
    git: https://github.com/cleandart/clean_backend
