name: clean_sync
description: A sample command-line application
dependencies:
  clean_data:
    git: https://github.com/hleumas/clean_data
  clean_server:
    git: https://github.com/hleumas/clean_server
  mongo_dart: any
